<!DOCTYPE html><html lang="es"><head><title>Editar</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"></head><body class="bg-light"><div class="container mt-5" style="max-width:800px"><div class="card shadow"><div class="card-header bg-warning">Editar Proyecto</div><div class="card-body"><form action="" method="POST">
<div class="mb-3"><label>Título</label><textarea name="titulo" class="form-control"><?php echo $data['proyecto']['titulo']; ?></textarea></div>
<div class="row mb-3">
<div class="col-md-6"><label>Facultad</label><select name="id_facultad" id="selFac" class="form-select" onchange="loadProg()"><?php foreach($data['facultades'] as $f): ?><option value="<?php echo $f['id']; ?>" <?php echo ($f['id']==$data['proyecto']['id_facultad'])?'selected':''; ?>><?php echo $f['nombre']; ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label>Programa</label><select name="id_programa" id="selProg" class="form-select"><?php foreach($data['programas'] as $pr): ?><option value="<?php echo $pr['id']; ?>" <?php echo ($pr['id']==$data['proyecto']['id_programa'])?'selected':''; ?>><?php echo $pr['nombre']; ?></option><?php endforeach; ?></select></div>
</div>
<div class="row mb-3">
<div class="col-md-6"><label>Asesor</label><select name="id_asesor" class="form-select"><?php foreach($data['docentes'] as $d): ?><option value="<?php echo $d['id']; ?>" <?php echo ($d['id']==$data['proyecto']['id_asesor'])?'selected':''; ?>><?php echo $d['apellidos'].' '.$d['nombres']; ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label>Nivel</label><select name="nivel" class="form-select"><option <?php echo ($data['proyecto']['nivel_academico']=='Pregrado')?'selected':''; ?>>Pregrado</option><option <?php echo ($data['proyecto']['nivel_academico']=='Posgrado')?'selected':''; ?>>Posgrado</option><option <?php echo ($data['proyecto']['nivel_academico']=='Segunda Especialidad')?'selected':''; ?>>Segunda Especialidad</option></select></div>
</div>
<div class="mb-3"><label>Línea de Investigación</label><select name="id_sublinea" class="form-select">
<?php foreach($data['jerarquia'] as $a): ?><optgroup label="<?php echo $a['nombre']; ?>"><?php if(isset($a['lineas'])) foreach($a['lineas'] as $l): if(isset($l['sublineas'])) foreach($l['sublineas'] as $s): ?><option value="<?php echo $s['id']; ?>" <?php echo ($s['id']==$data['proyecto']['id_linea_investigacion'])?'selected':''; ?>><?php echo $l['nombre'].' - '.$s['nombre']; ?></option><?php endforeach; endforeach; ?></optgroup><?php endforeach; ?>
</select></div>
<div class="mb-3 bg-light p-3 border"><label class="fw-bold">Estado / Etapa</label><select name="estado_fase" class="form-select">
<?php $c=$data['proyecto']['estado'].'|'.$data['proyecto']['id_etapa_actual']; ?>
<optgroup label="Fase 1"><option value="Iniciado|1" <?php echo ($c=='Iniciado|1')?'selected':''; ?>>Iniciado</option><option value="En Revisión|1" <?php echo ($c=='En Revisión|1')?'selected':''; ?>>En Revisión (P)</option><option value="Observado|1" <?php echo ($c=='Observado|1')?'selected':''; ?>>Observado (P)</option><option value="Aprobado|1" <?php echo ($c=='Aprobado|1')?'selected':''; ?>>Aprobado (P)</option></optgroup>
<optgroup label="Fase 2"><option value="En Revisión|2" <?php echo ($c=='En Revisión|2')?'selected':''; ?>>En Revisión (B)</option><option value="Observado|2" <?php echo ($c=='Observado|2')?'selected':''; ?>>Observado (B)</option><option value="Aprobado|2" <?php echo ($c=='Aprobado|2')?'selected':''; ?>>Aprobado (B)</option></optgroup>
<optgroup label="Fase 3"><option value="En Sustentación|3" <?php echo ($c=='En Sustentación|3')?'selected':''; ?>>En Sustentación</option><option value="Sustentado|3" <?php echo ($c=='Sustentado|3')?'selected':''; ?>>Sustentado</option></optgroup>
</select></div>
<button class="btn btn-success w-100">Guardar</button></form></div></div></div>
<script>async function loadProg(){const fid=document.getElementById('selFac').value;const sel=document.getElementById('selProg');sel.innerHTML='<option>Cargando...</option>';const fd=new FormData();fd.append('id_facultad',fid);const r=await fetch('<?php echo URL_BASE; ?>api/get_programas',{method:'POST',body:fd});const d=await r.json();sel.innerHTML='';d.forEach(p=>{sel.innerHTML+='<option value="'+p.id+'">'+p.nombre+'</option>'});}</script></body></html>
